version: '3.8'

services:
  memgraph:
    image: memgraph/memgraph-platform:latest
    ports:
      - "7687:7687"
      - "9091:9091"
    environment:
      - MEMGRAPH_USER=
      - MEMGRAPH_PASSWORD=
    restart: always
